/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignmenttwo;

import data.Employee;
import data.EmployeeDirectory;
import java.awt.CardLayout;
import java.awt.Image;
import java.time.LocalDate;
import javax.swing.JPanel;
import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;

/**
 *
 * @author gunjitarora
 */
public class AddPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPanel
     */
    
    String employeeId;
    EmployeeDirectory employeeDirectory;
    JPanel mainPanel;
    CardLayout cardLayout;
    LocalDate today;
    Image profileImage;
    Employee employee;
    
    public AddPanel() {
        initComponents();
        today = LocalDate.now();
        this.mainPanel = mainPanel;
        this.employeeId = employeeId;
        cardLayout = (CardLayout) mainPanel.getLayout();
        this.employeeDirectory = employeeDirectory;
        DatePickerSettings birthDateSettings = new DatePickerSettings();
        birthDateSettings.setAllowKeyboardEditing(false);
        birthDateSettings.setAllowEmptyDates(false);
        birthDateSettings.setFirstDayOfWeek(DayOfWeek.MONDAY);
        birthDatePicker.setSettings(birthDateSettings);
        DatePickerSettings startDateSettings = new DatePickerSettings();
        startDateSettings.setAllowKeyboardEditing(false);
        startDateSettings.setAllowEmptyDates(false);
        startDateSettings.setFirstDayOfWeek(DayOfWeek.MONDAY);
        startDatePicker.setSettings(startDateSettings);
        
        birthDateSettings.setDateRangeLimits(LocalDate.MIN, today.minusYears(18));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
